### ISSUE TITLE
Is it possible to pass MSAAuthAndroidAdapter constructor just the context?

### ISSUE THREAD

**Issue by kumaraish** [microsoftgraph/msgraph-sdk-android-msa-auth-for-android-adapter#5]
This is what is being done in MSAAuthAndroidAdapter constructor - 

>   public MSAAuthAndroidAdapter(final Application application) {
>           mLogger = new DefaultLogger();
>           application.getBaseContext();
>           mLiveAuthClient = new LiveAuthClient(
>                   application.getApplicationContext(),
>                   getClientId(),
>                   Arrays.asList(getScopes()),
>                   MicrosoftOAuth2Endpoint.getInstance());
>   }

As can be seen, the only real requirement on MSAAuthAndroidAdapter is the application context. 
and `application.getBaseContext();` is not serving any purpose here?

Then is it possible to change MSAAuthAndroidAdapter to accept just a Context ?

**Comment by peternied** [comment]
This adapters interface was built to be as generic as possible so when a fully supported authentication library is released, substituting in this interface would be trivial for consumers.  Not knowing the requirements of this future system, changing the interface at this time does not seem productive.

Is there a reason that Application is harder to use/obtain that the context?

To your point about `application.getBaseContext();` this is not needed, and a typo that slipped in.

**Comment by kumaraish** [comment]
Nothing specific hard/problematic with using Application I can think of right now. However, use of Application here is more than what is needed; indicates some dependency on may be extending Application object in the future; moreover, my app integrates multiple cloud services and is designed around using Contexts only which are sufficient for the purpose.

**Comment by modislaszlox2** [comment]
I also need this change. There is no reason to use application. Every well implemented sdk is using either context.

**Comment by tensory** [comment]
@peternied Application is easiest to obtain when calling this library directly within an Activity. In other situations, such as from a RecyclerView.Adapter.ViewHolder.onBindView, it is easy to get a Context but direct access to the Application is not provided. 

In my exploration with this library, I was already requiring a Context as a constructor parameter. Dropping this library in required adding the Application as well (and getting the needed Context from it), which imposes the new requirement that the class can only be constructed where an Application is available, or via specially-built factories that pass a reference to it. Since only the context and no other attribute of Application is required by LiveAuthClient,  this interface is not optimally generic.

**Comment by baywet** [comment]
Hi everyone,
Thank you for the contribution, we have moved away from an android specific SDK to a [Java SDK](https://github.com/microsoftgraph/msgraph-sdk-java) and this repo will be archived very soon.
If you're still facing the same issue with the Java SDK, feel free to re-open an issue over there.
Closing.
