### ISSUE TITLE
Public access to Access and Refresh tokens

### ISSUE THREAD

**Issue by nawar** [microsoftgraph/msgraph-sdk-android-msa-auth-for-android-adapter#8]
I've been trying to find a way to do this; however, the field which provides access to the **Access** and **Refresh** tokens is private. This field is     

```java
private final LiveAuthClient mLiveAuthClient;
```
to be able to do this:
```java
final String accessToken = mLiveAuthClient.getSession().getAccessToken();
final String refreshToken = mLiveAuthClient.getSession().refreshToken();
```

Ideally, it's very useful to store the access and refresh tokens in the server and use them to process information on the behalf of the user.

**Comment by kassim** [comment]
^ I need exactly the same feature

**Comment by kassim** [comment]
I've provided the feature here https://github.com/microsoftgraph/msgraph-sdk-android-msa-auth-for-android-adapter/pull/10

**Comment by clxy** [comment]
I need this feature too.
Without that, my user have to do the authentication again when the access token is expired.

It seems quite difficult to get those Refresh tokens. 
Since LiveAuthClient do not get refresh tokens by default,
You must start a new TokenRequest to archive that.
But most of those classes are package-private!

**Comment by baywet** [comment]
Hi everyone,
Thank you for the contribution, we have moved away from an android specific SDK to a [Java SDK](https://github.com/microsoftgraph/msgraph-sdk-java) and this repo will be archived very soon.
If you're still facing the same issue with the Java SDK, feel free to re-open an issue over there.
Closing.
